"""Schema definitions for all layers."""

from .bronze import (
    TRANSACTIONS_SCHEMA as BRONZE_TRANSACTIONS_SCHEMA,
    CUSTOMERS_SCHEMA as BRONZE_CUSTOMERS_SCHEMA,
    MERCHANTS_SCHEMA as BRONZE_MERCHANTS_SCHEMA,
    EXCHANGE_RATES_SCHEMA as BRONZE_EXCHANGE_RATES_SCHEMA,
)

from .silver import (
    TRANSACTIONS_SCHEMA as SILVER_TRANSACTIONS_SCHEMA,
    CUSTOMERS_SCHEMA as SILVER_CUSTOMERS_SCHEMA,
    MERCHANTS_SCHEMA as SILVER_MERCHANTS_SCHEMA,
)

__all__ = [
    "BRONZE_TRANSACTIONS_SCHEMA",
    "BRONZE_CUSTOMERS_SCHEMA",
    "BRONZE_MERCHANTS_SCHEMA",
    "BRONZE_EXCHANGE_RATES_SCHEMA",
    "SILVER_TRANSACTIONS_SCHEMA",
    "SILVER_CUSTOMERS_SCHEMA",
    "SILVER_MERCHANTS_SCHEMA",
]
